import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: {
    locale?: string | undefined
  }
}) {
  return (
    <html lang={locale} className="antialiased">
      <body className={inter.className}>
        {children}
        <Footer />
      </body>
    </html>
  )
}
