import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Footer from '@/components/footer'
import Navbar from '@/components/navbar'
import { notFound } from 'next/navigation'
import { useTranslations } from 'next-intl'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const locales = ['en', 'pt']

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: {
    locale: string
  }
}) {
  if (!locales.includes(locale)) notFound()

  return (
    <html lang={locale} className="antialiased">
      <body className={inter.className}>
        <Navbar lang={locale} />
        {children}
        <Footer />
      </body>
    </html>
  )
}
